openapi: 3.0.0
info:
  title: Logistics App API
  description: Logistics API by Oghenero Ologe
  contact:
    name: Oghenero Ologe
    email: nologe37@gmail.com
  version: 1.0.0
paths:
  /users:
    description: User Resource
    get:
      description: Operation to get current user
      responses:
        200:
          description: Success Response
          content:
            schema:
              type: object
              properties:
                _id:
                  type: ObjectID
                username:
                  type: String
                email:
                  type: String
                phone_number:
                  type: Number
                otp_verified: 